# Generated by Django 5.1.3 on 2024-11-15 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Уникальный uid')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('EUR', 'EUR')], max_length=3, verbose_name='ISO код валюты')),
                ('balance', models.BigIntegerField(default=0, verbose_name='Баланс в копейках или центах')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=30, verbose_name='Тип транзакции')),
                ('amount', models.BigIntegerField(verbose_name='Сумма в копейках или центах')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Транзакции', to='account.account')),
            ],
        ),
    ]
